name: Inline config
on: [push]


jobs:
  read-config:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: List files
      run: ls -al

    - id: read-config
      run: |
        config=$(cat cicd_config.json)
        echo "CICD_CONFIG_JSON=$(echo $config | jq -c .)" >> $GITHUB_OUTPUT
        
    outputs:
      cicd-config-json: ${{ steps.read-config.outputs.CICD_CONFIG_JSON }}

  parser-printer:
    runs-on: ubuntu-latest
    needs: ["read-config"]
    steps:
      - run: |
          echo "Hello from: {{ fromJSON(needs.read-config.outputs.cicd-config-json).PROJECT_KEY_DEV }}"



