name: Parse Config and Set Env Vars

on:
  workflow_call:
    inputs:
      config-path:
        description: 'Path to the config.json file'
        type: string
        required: true
        default: 'cicd_config.json'

jobs:
  parse-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read and parse config.json
        id: parse_config
        run: |
          CONFIG_PATH="${{ inputs.config-path }}"
          if [ ! -f "$CONFIG_PATH" ]; then
            echo "Config file not found: $CONFIG_PATH"
            exit 1
          fi
          CONFIG=$(cat "$CONFIG_PATH")
          echo "::set-output name=config::$CONFIG"

      - name: Set environment variables
        id: set_env
        run: |
          echo "Parsing ${{ inputs.config-path }} and setting environment variables..."
          for key in $(echo ${{ steps.parse_config.outputs.config }} | jq -r 'keys[]'); do
            value=$(echo ${{ steps.parse_config.outputs.config }} | jq -r --arg k "$key" '.[$k]')
            echo "Setting $key=$value"
            echo "$key=$value" >> $GITHUB_ENV
          done
        env:
          CONFIG_JSON: ${{ steps.parse_config.outputs.config }}

      - name: Export config
        run: echo "config=${{ steps.parse_config.outputs.config }}" >> $GITHUB_ENV
