name: Use Config from Reusable Workflow

on: [push, pull_request]

jobs:
  use-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call reusable workflow
        id: call_parse_config
        uses: JakubCee/ghact/.github/workflows/read_config.yml@main
        with:
          config-path: 'cicd_config.json'


      - name: Print environment variables (for debugging)
        run: |
          echo "PROJECT_KEY_DEV: $PROJECT_KEY_DEV"
          echo "PROJECT_KEY_TEST: $PROJECT_KEY_TEST"
          echo "TEST_SCENARIOS: $TEST_SCENARIOS"
